### ISSUE TITLE
CL50 - Add Financial information to stage card in DOM

### ISSUE THREAD

**Issue by daveholst** [busy-boys/movie-master#15]
### TODO:

- [x] mock template html up on index.html
- [x] write a domBuilder function that can hit the profit fetch function #6 and can append appropraite objects (innerHTML) to the DOM
- [x] set it be invoked at the end of the domBuilder function that builds the stagecard #12

**Comment by daveholst** [comment]
I had a play around with this 'off branch' and I think this will do the trick. It's not super fancy, but can be tarted up a bit if we have time. 

![image](https://user-images.githubusercontent.com/46893433/115105859-1dde0d80-9f94-11eb-9ef0-ee2466ff6562.png)

Dom builder steps required NOTE: this is only for the 'finances footer'

- [x] create div with `class = "card-footer"
- [x] add the follow innerHTML as string literal and fill in variables ( + some maths)
```html
                <p class="card-footer-item">
                  <span><b>Budget (2005)</b> $6,000,000</span>
                </p>
                <p class="card-footer-item">
                  <span> <b>Revenue (2005)</b> $245,066,411 </span>
                </p>
              </div>
              <div class="card-footer">
                <p class="card-footer-item">
                  <span><b>Budget (2021)</b> $8,395,299</span>
                </p>
                <p class="card-footer-item">
                  <span> <b>Revenue (2021)</b> $342,900,998 </span>
                </p>
              </div>
              <div class="card-footer">
                <p class="card-footer-item">
                  <span><b>Profit</b> $239,066,411</span>
                </p>
                <p class="card-footer-item">
                  <span><b>ROI:</b> 4083 %</span>
                </p>
              </div>
```
- [x] append either to `#stage-card-left` or `#stage-card-right`

**Comment by daveholst** [comment]
Now I look at it, it should prob go:
```
Budget 2005  Budget 2021
Revenue 2005 Revenue 2021
ROI          Profit 2021
```
